source 'https://github.com/CocoaPods/Specs.git'


target 'FZValidationTextField_Example', :exclusive => true do
  pod "FZValidationTextField", :path => "../"
end

target 'FZValidationTextField_Tests', :exclusive => true do
  pod "FZValidationTextField", :path => "../"

  pod 'FBSnapshotTestCase'
end
